# This is a basic workflow to help you get started with Actions

name: gpks-backend-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch

env: 
  root: ./graduation-project-system-backend/


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deb-package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Installing system build prerequisites
        run: |
          sudo apt install -y ruby ruby-dev rubygems build-essential python3.8 python3.8-pip python3.8-setuptools python3.8-venv python3.8-wheel
          sudo gem install --no-document fpm
      
      - name: Check python version
        run: python3.8 --version
      
      - name: Installing Python build prerequisites
        run: python3.8 -m pip install -U PyInstaller

      - name: Show contents of directory
        run: ls -lah ${{ env.root }}

      - name: Installing Python project dependencies
        run: python3.8 -m pip install -r ${{env.root}}/requirements.txt


      - name: Bundle with PyInstaller
        run: python3.8 -m PyInstaller --distpath ${{env.root}}/dist ${{env.root}}/server.py --onefile -n gpks-server


      - name: Pack executable into deb-package
        run: fpm --config-files ${{env.root}}/config.yml -t deb -n gpks-server -s dir ${{env.root}}/dist/gpks-server/=/usr/bin/gpks-server ${{env.root}}/config.yml=/etc/gpks-server/config.yml

  
  download-deb-package:
    runs-on: ubuntu-latest
    needs: build-deb-package
    steps:
      - name: Download built deb-package
        uses: actions/download-artifact@v2
        with:
          name: gpks-server-linux


      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
