# This is a basic workflow to help you get started with Actions

name: gpks-backend-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deb-package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Switch to backend project directory
        run: cd $GITHUB_WORKSPACE/graduation-project-system-backend/

      - name: Installing system build prerequisites
        run: |
          sudo apt install ruby ruby-dev rubygems build-essential python3 python3-pip python3-setuptools
          sudo gem install --no-document fpm
      
      - name: Check python version
        run: python3 --version
      
      - name: Installing Python build prerequisites
        run: python3 -m pip install -U PyInstaller

      - name: Installing Python project dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Bundle with PyInstaller
        run: python3 -m PyInstaller ./server.py --onefile -n gpks-server

      - name: Pack executable into deb-package
        run: fpm --config-files ./config.yml -t deb -n gpks-server -s dir ./dist/gpks-server/=/usr/bin/gpks-server ./config.yml=/etc/gpks-server/config.yml
  
  download-deb-package:
    runs-on: ubuntu-latest
    needs: build-deb-package
    steps:
      - name: Download built deb-package
        uses: actions/download-artifact@v2
        with:
          name: gpks-server-linux


      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
